/// <reference types="expo/types" />

// NOTE: This file should not be edited and should be committed with your source code. It is generated by Expo. If you need to move or disable this file, please see the documentation: https://docs.expo.dev/guides/typescript/#tsconfigjson
